// Copyright 2026 BitWise Media Group Ltd
// SPDX-License-Identifier: MIT

package harness

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"

	"github.com/codeactual/evolve/internal/model"
)

// Codex drives the `codex` CLI (OpenAI Codex).
type Codex struct {
	base
}

// NewCodex returns the builtin Codex harness.
func NewCodex() *Codex {
	return &Codex{base: base{
		id:        model.HarnessCodex,
		name:      "OpenAI Codex",
		clis:      []string{"codex"},
		envKeys:   []string{"EVOLVE_OPENAI_API_KEY", "OPENAI_API_KEY"},
		skillDirs: []string{filepath.Join(".agents", "skills")},
	}}
}

// codexHomeRel is the workspace-relative CODEX_HOME evolve gives the codex
// CLI. Sessions, history.jsonl, and the memory store live here so runs do not
// touch the operator's real ~/.codex; the tree dies with the workspace.
// Project skills stay at .agents/skills (the skillDirs mount).
const codexHomeRel = ".evolve/codex-home"

// codexEnv returns the process env extras for a codex invocation in ws:
// isolated CODEX_HOME with the operator's auth bridged in.
func codexEnv(ws string) []string {
	home := isolatedDir(ws, codexHomeRel)
	ensureCodexHome(home)
	return []string{"CODEX_HOME=" + home}
}

// ensureCodexHome creates the isolated home, links the operator's auth.json
// (write-through so a mid-run token refresh sticks), and carries over the
// credential-store selection. Best-effort per the isolate.go contract.
func ensureCodexHome(home string) {
	if err := os.MkdirAll(home, 0o755); err != nil {
		return
	}
	srcHome := operatorDir("CODEX_HOME", ".codex")
	if srcHome == "" || sameFilePath(srcHome, home) {
		return
	}
	linkFile(filepath.Join(srcHome, "auth.json"), filepath.Join(home, "auth.json"))
	seedCodexConfig(srcHome, home)
}

// seedCodexConfig writes a minimal config.toml into the isolated home carrying
// only the operator's cli_auth_credentials_store selection: keyring-stored
// credentials are global to the user, but codex only consults the keyring when
// config.toml says so. Everything else in the operator config (MCP servers,
// profiles, trust) is deliberately left behind.
func seedCodexConfig(srcHome, home string) {
	dst := filepath.Join(home, "config.toml")
	if _, err := os.Lstat(dst); err == nil {
		return
	}
	data, err := os.ReadFile(filepath.Join(srcHome, "config.toml"))
	if err != nil {
		return
	}
	for line := range strings.Lines(string(data)) {
		if strings.HasPrefix(strings.TrimSpace(line), "cli_auth_credentials_store") {
			content := "# Generated by evolve for an isolated codex harness run.\n" +
				strings.TrimSpace(line) + "\n"
			_ = os.WriteFile(dst, []byte(content), 0o644)
			return
		}
	}
}

func (c *Codex) TriggerSpec(ws, query, cliModelID string, hostSandboxed bool) model.CommandSpec {
	argv := []string{"codex", "exec", query, "--json", "--skip-git-repo-check", "-m", cliModelID}
	if hostSandboxed {
		// codex defaults to a read-only Seatbelt sandbox even for exec; that nests
		// illegally inside evolve's, so disable it and let evolve confine.
		argv = append(argv, "--sandbox", "danger-full-access")
	}
	return model.CommandSpec{Argv: argv, Dir: ws, Env: codexEnv(ws)}
}

// ScanLine is best-effort: any event-stream line mentioning the skill's
// SKILL.md path counts as an activation.
func (c *Codex) ScanLine(line []byte, skill, _ string) (bool, string) {
	return strings.Contains(string(line), "skills/"+skill+"/SKILL.md"), ""
}

func (c *Codex) EvalSpec(ws string, in model.EvalInput, cliModelID string) model.CommandSpec {
	// codex applies its own macOS Seatbelt sandbox for read-only/workspace-write,
	// which cannot nest inside evolve's. When evolve already confines the run,
	// switch codex to danger-full-access so evolve's sandbox is the sole layer;
	// otherwise keep workspace-write as codex's own confinement.
	sandboxMode := "workspace-write"
	if in.HostSandboxed {
		sandboxMode = "danger-full-access"
	}
	return model.CommandSpec{
		Argv: []string{
			"codex", "exec", in.Prompt,
			"--json", "--skip-git-repo-check",
			"--sandbox", sandboxMode,
			"-m", cliModelID,
		},
		Dir: ws,
		Env: codexEnv(ws),
	}
}

// ParseEvalOutput concatenates agent messages from the codex event stream and
// captures the last turn's usage. Codex reports tokens but not cost; the engine
// prices the tokens from the model matrix.
func (c *Codex) ParseEvalOutput(stdout []byte) (string, *model.Usage) {
	var texts []string
	var usage *model.Usage
	for line := range strings.SplitSeq(string(stdout), "\n") {
		var event struct {
			Type string `json:"type"`
			Item struct {
				Type string `json:"type"`
				Text string `json:"text"`
			} `json:"item"`
			Usage *struct {
				InputTokens       *int `json:"input_tokens"`
				CachedInputTokens *int `json:"cached_input_tokens"`
				OutputTokens      *int `json:"output_tokens"`
			} `json:"usage"`
		}
		if json.Unmarshal([]byte(line), &event) != nil {
			continue
		}
		if event.Type == "item.completed" && event.Item.Type == "agent_message" {
			texts = append(texts, event.Item.Text)
		}
		if event.Type == "turn.completed" && event.Usage != nil {
			// Codex reports input_tokens as the whole prompt with
			// cached_input_tokens a subset of it. The Usage contract wants fresh
			// (uncached) input on InputTokens and cache hits reported separately,
			// so split the cached portion off rather than letting re-read context
			// inflate the headline input figure.
			u := &model.Usage{OutputTokens: event.Usage.OutputTokens}
			if in := event.Usage.InputTokens; in != nil {
				fresh := *in
				if cached := event.Usage.CachedInputTokens; cached != nil {
					read := min(*cached, fresh)
					fresh -= read
					u.CacheReadTokens = &read
				}
				u.InputTokens = &fresh
			}
			usage = u
		}
	}
	if len(texts) == 0 {
		return string(stdout), usage
	}
	return strings.Join(texts, "\n"), usage
}

// ParseToolCalls returns the tool invocations in the codex event stream, in
// observed order. Tool names are codex's native item types: a shell command
// surfaces as "command_execution" (its `command` is the matchable argument) and
// an edit as "file_change" (its `changes` list the paths). These two are pinned
// to captured `codex exec --json` output; mcp_tool_call and function_call are
// documented codex tool items not present in the capture, so they surface under
// their item type with the whole item JSON as arguments rather than guessing the
// field layout. Only completed items count, so each call is reported once.
func (c *Codex) ParseToolCalls(stdout []byte) []model.ToolCall {
	var calls []model.ToolCall
	for line := range strings.SplitSeq(string(stdout), "\n") {
		var event struct {
			Type string          `json:"type"`
			Item json.RawMessage `json:"item"`
		}
		if json.Unmarshal([]byte(line), &event) != nil || event.Type != "item.completed" {
			continue
		}
		var item struct {
			Type string `json:"type"`
		}
		if json.Unmarshal(event.Item, &item) != nil {
			continue
		}
		if tc, ok := codexToolCall(item.Type, event.Item); ok {
			calls = append(calls, tc)
		}
	}
	return calls
}

// codexToolCall maps one completed codex item to a tool call, or ok=false when
// the item is not a tool invocation (agent_message, reasoning, …). See
// ParseToolCalls for which item types are pinned versus handled defensively.
func codexToolCall(itemType string, raw json.RawMessage) (model.ToolCall, bool) {
	switch itemType {
	case "command_execution":
		var it struct {
			Command string `json:"command"`
		}
		_ = json.Unmarshal(raw, &it)
		input, _ := json.Marshal(it.Command) // match the invocation, not its output
		return model.ToolCall{Name: itemType, Input: input}, true
	case "file_change":
		var it struct {
			Changes json.RawMessage `json:"changes"`
		}
		_ = json.Unmarshal(raw, &it)
		return model.ToolCall{Name: itemType, Input: it.Changes}, true
	case "mcp_tool_call", "function_call":
		return model.ToolCall{Name: itemType, Input: raw}, true
	default:
		return model.ToolCall{}, false
	}
}

// codexModelListStdin is the JSON-RPC conversation fed to `codex app-server`
// to read the operator's model-picker list: the mandatory initialize
// handshake, then model/list (id 2). Hidden models are deliberately excluded —
// the probe mirrors what the CLI's own picker offers the account. The server
// serves stdio forever, so the probe's done predicate kills it once the id-2
// response line arrives.
const codexModelListStdin = `{"jsonrpc":"2.0","id":1,"method":"initialize",` +
	`"params":{"clientInfo":{"name":"evolve","title":"evolve","version":"0.0.0"}}}` + "\n" +
	`{"jsonrpc":"2.0","method":"initialized"}` + "\n" +
	`{"jsonrpc":"2.0","id":2,"method":"model/list","params":{}}` + "\n"

// ListOfferedModels asks the installed codex CLI which models the operator's
// account is offered, via the app-server protocol's model/list request — the
// same source the CLI's interactive picker renders. Probes run against the
// operator's real CODEX_HOME on purpose; the isolated home agent runs use
// would hide the account-dependent list being probed.
func (c *Codex) ListOfferedModels(ctx context.Context, probe ProbeExec) ([]string, error) {
	spec := model.CommandSpec{
		Argv:  []string{"codex", "app-server"},
		Stdin: []byte(codexModelListStdin),
	}
	out, err := probe(ctx, spec, func(line []byte) bool {
		_, done := parseCodexModelList(line)
		return done
	})
	if err != nil {
		return nil, err
	}
	for line := range strings.SplitSeq(string(out), "\n") {
		if offered, ok := parseCodexModelList([]byte(line)); ok {
			return offered, nil
		}
	}
	return nil, nil
}

// parseCodexModelList decodes one app-server stdout line, returning the
// offered model tokens when the line is the model/list response (id 2). Each
// model contributes its CLI model id (`model`, what -m accepts) and its
// display name, deduplicated.
func parseCodexModelList(line []byte) (offered []string, ok bool) {
	var resp struct {
		ID     *int `json:"id"`
		Result *struct {
			Data []struct {
				Model       string `json:"model"`
				DisplayName string `json:"displayName"`
			} `json:"data"`
		} `json:"result"`
	}
	if json.Unmarshal(line, &resp) != nil || resp.ID == nil || *resp.ID != 2 || resp.Result == nil {
		return nil, false
	}
	seen := map[string]bool{}
	for _, m := range resp.Result.Data {
		for _, tok := range []string{m.Model, m.DisplayName} {
			if tok != "" && !seen[tok] {
				seen[tok] = true
				offered = append(offered, tok)
			}
		}
	}
	return offered, true
}

// ReportsUsage reports that codex reports token usage (cost is computed from
// pricing).
func (c *Codex) ReportsUsage() bool { return true }

// RuntimeError detects a codex run that produced no agent output (auth blocked,
// crash) so it is reported distinctly from a failed eval. A run that emitted any
// agent_message event is gradable, regardless of exit code.
func (c *Codex) RuntimeError(stdout []byte, exitCode int, timedOut bool) string {
	if len(bytes.TrimSpace(stdout)) == 0 {
		return "empty CLI output"
	}
	for line := range strings.SplitSeq(string(stdout), "\n") {
		var event struct {
			Type string `json:"type"`
			Item struct {
				Type string `json:"type"`
			} `json:"item"`
		}
		if json.Unmarshal([]byte(line), &event) != nil {
			continue
		}
		if event.Type == "item.completed" && event.Item.Type == "agent_message" {
			return "" // produced agent output — gradable
		}
	}
	if exitCode != 0 {
		return "codex produced no agent output"
	}
	return ""
}
